export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_VERIFY_TOKEN = "AUTH_VERIFY_TOKEN";
export const AUTH_REFRESH_TOKEN = "AUTH_REFRESH_TOKEN";
